import type { AnyReport, CompareReport } from "../index.js";
import type { SimulationResult } from "../core/runner.js";
import type { ValidationIssue } from "../schema/validate.js";
import { fmtDeltaMin, type EconomyRow, type Finding, type FlowShare, type Insights, type PacingView, type ScenarioView } from "../insights/insights.js";
import { fmtMin, num, pct, signedPct } from "./units.js";

/**
 * Self-contained static dashboard (docs/dashboard-design.md §6).
 * No JavaScript, no external assets: inline CSS + server-rendered SVG.
 * The source report is embedded as JSON in <script type="application/json" id="gdl-report">.
 */
export function renderHtml(report: AnyReport, ins: Insights): string {
  const p = report.provenance;
  const sim = primarySim(report);
  const sections: string[] = [];
  const nav: [string, string][] = [["findings", "Findings"]];

  sections.push(findingsSection(ins.findings));
  if (ins.pacing && sim) {
    nav.push(["pacing", "Pacing"]);
    sections.push(pacingSection(ins.pacing, sim));
  }
  if (ins.economy && sim) {
    nav.push(["economy", "Economy"]);
    sections.push(economySection(ins.economy, ins.actionUsage ?? []));
  }
  if (report.kind === "compare" && ins.scenarios) {
    nav.push(["scenarios", "Scenarios"]);
    sections.push(scenarioSection(report, ins.scenarios));
  }
  nav.push(["validation", "Validation"]);
  sections.push(validationSection(report));

  const title = `GDL ${report.kind} — ${p.project.id}`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="GDL ${esc(p.gdlVersion)}">
<title>${esc(title)}</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <div class="title"><h1>${esc(p.project.id)}</h1><span class="kind">${esc(report.kind)}</span>${badge(report.validation.ok ? "ok" : "critical", report.validation.ok ? "valid" : "INVALID")}</div>
  <dl class="prov">
    ${dt("adapter", `${p.adapter.id}@${p.adapter.version} (api ${p.adapter.apiVersion})`)}
    ${dt("model", p.modelSha256.slice(0, 16) + "…", p.modelSha256)}
    ${dt("sources", p.sources.map((s) => s.path).join(", ") || "-")}
    ${sim ? dt("run", `${sim.mode}${sim.seed !== null ? ` · ${sim.runs} runs · seed ${sim.seed}` : ""} · limit ${fmtMin(sim.limits.maxMinutes)} / ${sim.limits.maxActions} actions`) : ""}
    ${sim ? dt("policy", `${sim.policy.id}${sim.policy.implicit ? " (implicit)" : ""}`, sim.policy.actions.join(" > ")) : ""}
    ${dt("generated", `${p.generatedAt} · GDL ${p.gdlVersion} · report ${p.reportVersion}`)}
  </dl>
  <nav>${nav.map(([id, label]) => `<a href="#${id}">${label}</a>`).join("")}</nav>
</header>
<main>
${sections.join("\n")}
</main>
<footer>
${report.unsupported.length ? `<h3>Not modelled — results do not cover these (declared by adapter)</h3><ul>${report.unsupported.map((u) => `<li><b>${esc(u.feature)}</b>: ${esc(u.reason)}</li>`).join("")}</ul>` : ""}
<p class="muted">Generated by GDL ${esc(p.gdlVersion)}. Findings are deterministic rules (docs/dashboard-design.md §5), not recommendations.</p>
</footer>
<script type="application/json" id="gdl-report">${embedJson(report)}</script>
</body>
</html>
`;
}

function primarySim(r: AnyReport): SimulationResult | undefined {
  if (r.kind === "compare") return r.baseline;
  if (r.kind === "validate") return undefined;
  return r.simulation;
}

// ---------------------------------------------------------------- sections

function findingsSection(fs: Finding[]): string {
  const c = { critical: 0, warning: 0, info: 0 };
  for (const f of fs) c[f.severity]++;
  const cards = fs.length
    ? fs.map((f) => `<div class="card ${f.severity}"><div class="card-h">${badge(f.severity, f.severity)}<span class="cat">${esc(f.category)}</span><span class="scope">${esc(f.scope)}</span></div><div class="card-t">${esc(f.title)}</div><div class="card-d">${esc(f.detail)}</div></div>`).join("")
    : `<p class="muted">No findings.</p>`;
  return `<section id="findings"><h2>Findings <small>${c.critical} critical · ${c.warning} warning · ${c.info} info</small></h2><div class="cards">${cards}</div></section>`;
}

function pacingSection(p: PacingView, s: SimulationResult): string {
  const parts: string[] = [`<section id="pacing"><h2>Pacing &amp; bottlenecks</h2>`];
  parts.push(`<div class="grid2"><div><h3>Arrival time per node <small>${s.mode === "monte-carlo" ? "bar = p10–p90, dot = median" : "expected value"}</small></h3>${rangeChart(p)}</div>`);
  parts.push(`<div><h3>Segment length <small>median time since previous node</small></h3>${segmentChart(p)}</div></div>`);
  parts.push(`<h3>How runs ended</h3>${stackBar(p.stops.map((x) => ({ key: x.reason, share: x.share, mean: x.share })), STOP_COLORS)}`);
  if (p.stalls.length) {
    parts.push(`<h3>Where progress stopped</h3><table><thead><tr><th>next node</th><th>runs</th><th>blocked by</th><th>limiting resource</th><th>gap</th><th>net/h</th><th>est. more play</th></tr></thead><tbody>`);
    for (const st of p.stalls) {
      const lims = st.limits.length ? st.limits : [null];
      lims.forEach((l, i) => {
        parts.push(`<tr>${i === 0 ? `<td rowspan="${lims.length}">${esc(st.node)}</td><td rowspan="${lims.length}" class="n">${pct(st.share)}</td><td rowspan="${lims.length}">${esc(st.reasons.join("; ") || "ran out of time/actions")}</td>` : ""}` +
          (l ? `<td>${esc(l.resource)}</td><td class="n">${num(l.gap)}</td><td class="n">${num(l.netPerHour)}</td><td class="n ${l.etaMinutes === null ? "bad" : ""}">${l.etaMinutes === null ? "does not close" : "~" + fmtMin(l.etaMinutes)}</td>` : `<td colspan="4" class="muted">-</td>`) + `</tr>`);
      });
    }
    parts.push(`</tbody></table>`);
  }
  parts.push(`</section>`);
  return parts.join("");
}

function economySection(rows: EconomyRow[], usage: { id: string; mean: number }[]): string {
  const parts: string[] = [`<section id="economy"><h2>Resource economy <small>means per run</small></h2>`];
  parts.push(`<table><thead><tr><th>resource</th><th>produced</th><th>consumed</th><th>final (median)</th><th>net / h</th><th>overflow</th></tr></thead><tbody>`);
  for (const r of rows) {
    parts.push(`<tr><td>${esc(r.id)}</td><td class="n">${num(r.produced)}</td><td class="n">${num(r.consumed)}</td><td class="n">${num(r.finalMedian)}</td><td class="n ${r.netPerHour < 0 ? "bad" : ""}">${num(r.netPerHour)}</td><td class="n ${r.overflow > 0 ? "warn" : ""}">${r.overflow > 0 ? `${num(r.overflow)} (${pct(r.overflowShare)})` : "-"}</td></tr>`);
  }
  parts.push(`</tbody></table><h3>Where each resource comes from and goes to</h3><div class="flows">`);
  for (const r of rows) {
    parts.push(`<div class="flow"><h4>${esc(r.id)}</h4><div class="flow-row"><span class="lbl">in</span>${r.sources.length ? stackBar(r.sources) : `<span class="muted">none</span>`}</div><div class="flow-row"><span class="lbl">out</span>${r.sinks.length ? stackBar(r.sinks) : `<span class="muted">none</span>`}</div></div>`);
  }
  parts.push(`</div>`);
  if (usage.length) parts.push(`<h3>Action usage <small>mean uses per run</small></h3>${hbar(usage.map((u) => ({ label: u.id, value: u.mean, text: num(u.mean), cls: u.mean === 0 ? "zero" : "" })))}`);
  parts.push(`</section>`);
  return parts.join("");
}

function scenarioSection(r: CompareReport, views: ScenarioView[]): string {
  const parts: string[] = [`<section id="scenarios"><h2>Scenario comparison <small>same seed as baseline (common random numbers)</small></h2>`];
  for (const v of views) {
    const sc = r.scenarios.find((x) => x.id === v.id)!;
    parts.push(`<div class="scenario"><h3>${esc(v.id)}${v.description ? ` <small>${esc(v.description)}</small>` : ""}</h3>`);
    parts.push(`<details><summary>${v.changes} value(s) changed</summary><table><thead><tr><th>op</th><th>path</th><th>before</th><th>after</th></tr></thead><tbody>${sc.applied.flatMap((a) => a.matches.map((m) => `<tr><td>${esc(a.op)}</td><td><code>${esc(m.path)}</code></td><td class="n">${esc(JSON.stringify(m.before))}</td><td class="n">${esc(JSON.stringify(m.after))}</td></tr>`)).join("")}</tbody></table></details>`);
    if (!v.valid) {
      parts.push(`<p class="bad">Scenario model is invalid; not simulated.</p>${issues(sc.validation.errors)}</div>`);
      continue;
    }
    const cr = v.completionRate!;
    parts.push(`<p>Completion rate <b>${pct(cr.baseline ?? 0)}</b> → <b class="${(cr.delta ?? 0) < 0 ? "bad" : (cr.delta ?? 0) > 0 ? "good" : ""}">${pct(cr.scenario ?? 0)}</b></p>`);
    if (sc.simulation && r.baseline) parts.push(`<h4>Median arrival: baseline vs scenario</h4>${dumbbell(r.baseline, sc.simulation)}`);
    if (v.nodeImpact.length) {
      parts.push(`<table><thead><tr><th>node (by impact)</th><th>median time</th><th>reach rate</th></tr></thead><tbody>`);
      for (const n of v.nodeImpact) {
        const d = n.medianMinute.delta;
        const cls = n.medianMinute.baseline !== null && n.medianMinute.scenario === null ? "bad" : d === null ? "" : d < 0 ? "good" : d > 0 ? "bad" : "";
        const rc = n.reachRate.delta ? `${pct(n.reachRate.baseline ?? 0)} → ${pct(n.reachRate.scenario ?? 0)}` : `${pct(n.reachRate.baseline ?? 0)} (=)`;
        parts.push(`<tr><td>${esc(n.id)}</td><td class="${cls}">${esc(fmtDeltaMin(n.medianMinute))}</td><td class="${(n.reachRate.delta ?? 0) < 0 ? "bad" : (n.reachRate.delta ?? 0) > 0 ? "good" : ""}">${rc}</td></tr>`);
      }
      parts.push(`</tbody></table>`);
    }
    if (v.resourceImpact.length) {
      parts.push(`<table><thead><tr><th>resource (by impact)</th><th>baseline final</th><th>scenario final</th><th>change</th></tr></thead><tbody>`);
      for (const x of v.resourceImpact) parts.push(`<tr><td>${esc(x.id)}</td><td class="n">${num(x.delta.baseline ?? 0)}</td><td class="n">${num(x.delta.scenario ?? 0)}</td><td class="n">${signedPct(x.delta.pct)}</td></tr>`);
      parts.push(`</tbody></table>`);
    }
    if (!v.nodeImpact.length && !v.resourceImpact.length) parts.push(`<p class="warn">No measurable change.</p>`);
    parts.push(`</div>`);
  }
  parts.push(`</section>`);
  return parts.join("");
}

function validationSection(r: AnyReport): string {
  const v = r.validation;
  return `<section id="validation"><h2>Validation <small>${v.errors.length} error(s) · ${v.warnings.length} warning(s)</small></h2>${v.errors.length + v.warnings.length ? issues([...v.errors, ...v.warnings]) : `<p class="good">Model passed schema and reference checks.</p>`}</section>`;
}

function issues(list: ValidationIssue[]): string {
  return `<table><thead><tr><th></th><th>code</th><th>path</th><th>message</th><th>source / hint</th></tr></thead><tbody>${list
    .map((i) => `<tr><td>${badge(i.severity === "error" ? "critical" : "warning", i.severity)}</td><td><code>${esc(i.code)}</code></td><td><code>${esc(i.path)}</code></td><td>${esc(i.message)}</td><td>${i.source ? esc(i.source.file + (i.source.path ? ` (${i.source.path})` : "")) : ""}${i.hint ? `<div class="muted">${esc(i.hint)}</div>` : ""}</td></tr>`)
    .join("")}</tbody></table>`;
}

// ---------------------------------------------------------------- charts (inline SVG)

const PALETTE = ["#4e79a7", "#f28e2b", "#59a14f", "#e15759", "#76b7b2", "#edc948", "#b07aa1", "#ff9da7", "#9c755f", "#bab0ac"];
const STOP_COLORS: Record<string, string> = { completed: "#59a14f", time_limit: "#4e79a7", action_limit: "#edc948", stuck: "#e15759" };
const LABEL_W = 170;
const CHART_W = 640;

function rangeChart(p: PacingView): string {
  const rowH = 24;
  const max = Math.max(1, ...p.nodes.map((n) => n.p90 ?? n.median ?? 0));
  const plotW = CHART_W - LABEL_W - 110;
  const x = (m: number) => LABEL_W + (m / max) * plotW;
  const h = p.nodes.length * rowH + 24;
  const rows = p.nodes.map((n, i) => {
    const y = i * rowH + 16;
    const label = `<text x="${LABEL_W - 8}" y="${y + 4}" text-anchor="end">${esc(n.id)}</text>`;
    if (n.median === null) return `${label}<text x="${LABEL_W}" y="${y + 4}" class="muted">not reached</text>`;
    const range = n.p10 !== null && n.p90 !== null && n.p90 > n.p10 ? `<rect x="${x(n.p10)}" y="${y - 5}" width="${Math.max(1, x(n.p90) - x(n.p10))}" height="10" rx="3" fill="#4e79a7" opacity="0.35"><title>p10 ${fmtMin(n.p10)} – p90 ${fmtMin(n.p90)}</title></rect>` : "";
    const reach = n.reachRate < 1 ? ` · ${pct(n.reachRate)}` : "";
    return `${label}<line x1="${LABEL_W}" x2="${LABEL_W + plotW}" y1="${y}" y2="${y}" class="grid"/>${range}<circle cx="${x(n.median)}" cy="${y}" r="4.5" fill="#4e79a7"><title>median ${fmtMin(n.median)}</title></circle><text x="${LABEL_W + plotW + 8}" y="${y + 4}">${fmtMin(n.median)}${reach}</text>`;
  });
  const axis = `<text x="${LABEL_W}" y="${h - 4}" class="muted">0</text><text x="${LABEL_W + plotW}" y="${h - 4}" text-anchor="end" class="muted">${fmtMin(max)}</text>`;
  return svg(CHART_W, h, rows.join("") + axis);
}

function segmentChart(p: PacingView): string {
  if (!p.segments.length) return `<p class="muted">Fewer than two nodes reached.</p>`;
  return hbar(p.segments.map((s) => ({ label: `→ ${s.to}`, value: s.medianMinutes, text: `${fmtMin(s.medianMinutes)}${s.share ? ` (${pct(s.share)})` : ""}`, cls: s === p.slowest ? "hot" : "" })));
}

function hbar(items: { label: string; value: number; text: string; cls?: string }[]): string {
  const rowH = 22;
  const max = Math.max(1e-9, ...items.map((i) => i.value));
  const plotW = CHART_W - LABEL_W - 120;
  const body = items.map((it, i) => {
    const y = i * rowH + 4;
    const w = it.value > 0 ? Math.max(2, (it.value / max) * plotW) : 0;
    return `<text x="${LABEL_W - 8}" y="${y + 13}" text-anchor="end">${esc(it.label)}</text><rect x="${LABEL_W}" y="${y + 3}" width="${w}" height="14" rx="2" class="bar ${it.cls ?? ""}"/><text x="${LABEL_W + w + 6}" y="${y + 14}" class="${it.value === 0 ? "muted" : ""}">${esc(it.text)}</text>`;
  });
  return svg(CHART_W, items.length * rowH + 8, body.join(""));
}

function stackBar(parts: FlowShare[], colors?: Record<string, string>): string {
  const w = 460;
  const total = parts.reduce((a, b) => a + b.share, 0) || 1;
  let x = 0;
  const rects: string[] = [];
  const legend: string[] = [];
  parts.forEach((p, i) => {
    const c = colors?.[p.key] ?? PALETTE[i % PALETTE.length]!;
    const pw = (p.share / total) * w;
    rects.push(`<rect x="${x}" y="0" width="${pw}" height="16" fill="${c}"><title>${esc(p.key)}: ${pct(p.share)} (${num(p.mean)})</title></rect>`);
    x += pw;
    legend.push(`<span class="lg"><i style="background:${c}"></i>${esc(p.key)} ${pct(p.share)}</span>`);
  });
  return `<div class="stack">${svg(w, 16, rects.join(""))}<div class="legend">${legend.join("")}</div></div>`;
}

function dumbbell(a: SimulationResult, b: SimulationResult): string {
  const rowH = 24;
  const nodes = a.nodes.map((n) => ({ id: n.id, a: n.minute?.median ?? null, b: b.nodes.find((x) => x.id === n.id)?.minute?.median ?? null }));
  const max = Math.max(1, ...nodes.flatMap((n) => [n.a ?? 0, n.b ?? 0]));
  const plotW = CHART_W - LABEL_W - 150;
  const x = (m: number) => LABEL_W + (m / max) * plotW;
  const body = nodes.map((n, i) => {
    const y = i * rowH + 16;
    let s = `<text x="${LABEL_W - 8}" y="${y + 4}" text-anchor="end">${esc(n.id)}</text><line x1="${LABEL_W}" x2="${LABEL_W + plotW}" y1="${y}" y2="${y}" class="grid"/>`;
    if (n.a !== null && n.b !== null) {
      const cls = n.b < n.a ? "good" : n.b > n.a ? "bad" : "";
      s += `<line x1="${x(n.a)}" x2="${x(n.b)}" y1="${y}" y2="${y}" class="db ${cls}"/>`;
    }
    if (n.a !== null) s += `<circle cx="${x(n.a)}" cy="${y}" r="4.5" fill="#999"><title>baseline ${fmtMin(n.a)}</title></circle>`;
    if (n.b !== null) s += `<circle cx="${x(n.b)}" cy="${y}" r="4.5" fill="#4e79a7"><title>scenario ${fmtMin(n.b)}</title></circle>`;
    const txt = n.a === null && n.b === null ? "not reached" : `${n.a === null ? "-" : fmtMin(n.a)} → ${n.b === null ? "-" : fmtMin(n.b)}`;
    return s + `<text x="${LABEL_W + plotW + 8}" y="${y + 4}" class="${n.a === null && n.b === null ? "muted" : ""}">${txt}</text>`;
  });
  const legend = `<text x="${LABEL_W}" y="${nodes.length * rowH + 20}" class="muted">● grey = baseline   ● blue = scenario</text>`;
  return svg(CHART_W, nodes.length * rowH + 28, body.join("") + legend);
}

function svg(w: number, h: number, body: string): string {
  return `<svg class="chart" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
}

// ---------------------------------------------------------------- helpers

function badge(kind: string, text: string): string {
  return `<span class="badge ${kind}">${esc(text)}</span>`;
}

function dt(k: string, v: string, title?: string): string {
  return `<div><dt>${esc(k)}</dt><dd${title ? ` title="${esc(title)}"` : ""}>${esc(v)}</dd></div>`;
}

export function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

/** JSON safe to place inside a <script> element. */
function embedJson(v: unknown): string {
  return JSON.stringify(v).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

const CSS = `
:root{--fg:#1f2328;--muted:#6e7781;--line:#d0d7de;--bg:#fff;--soft:#f6f8fa;--crit:#cf222e;--warn:#bc4c00;--info:#57606a;--good:#1a7f37;--accent:#4e79a7}
*{box-sizing:border-box}body{margin:0;font:14px/1.5 -apple-system,"Segoe UI","Noto Sans TC","Microsoft JhengHei",Helvetica,Arial,sans-serif;color:var(--fg);background:var(--bg)}
header{padding:20px 32px 0;border-bottom:1px solid var(--line);background:var(--soft)}
.title{display:flex;align-items:center;gap:12px}h1{margin:0;font-size:22px}.kind{font-size:13px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)}
.prov{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:4px 24px;margin:12px 0}.prov div{display:flex;gap:8px;min-width:0}
.prov dt{color:var(--muted);min-width:64px}.prov dd{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
nav{display:flex;gap:4px;position:sticky;top:0}nav a{padding:8px 14px;color:var(--fg);text-decoration:none;border-bottom:2px solid transparent}nav a:hover{border-color:var(--accent)}
main{padding:0 32px;max-width:1400px}section{padding:12px 0 24px;border-bottom:1px solid var(--line)}
h2{font-size:18px;margin:16px 0 8px}h3{font-size:15px;margin:18px 0 6px}h4{font-size:14px;margin:12px 0 4px}small{font-weight:normal;color:var(--muted);font-size:12px;margin-left:6px}
.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:10px}
.card{border:1px solid var(--line);border-left:4px solid var(--info);border-radius:6px;padding:10px 12px;background:var(--bg)}
.card.critical{border-left-color:var(--crit)}.card.warning{border-left-color:var(--warn)}
.card-h{display:flex;gap:8px;align-items:center;font-size:12px}.cat{font-weight:600}.scope{color:var(--muted);margin-left:auto}
.card-t{font-weight:600;margin:4px 0 2px}.card-d{color:var(--muted);font-size:13px}
.badge{display:inline-block;padding:0 8px;border-radius:10px;font-size:12px;color:#fff;background:var(--info)}.badge.critical{background:var(--crit)}.badge.warning{background:var(--warn)}.badge.ok{background:var(--good)}
table{border-collapse:collapse;margin:6px 0 10px;font-size:13px}th,td{border:1px solid var(--line);padding:4px 10px;text-align:left;vertical-align:top}th{background:var(--soft);font-weight:600}
td.n{text-align:right;font-variant-numeric:tabular-nums}.bad{color:var(--crit)}.good{color:var(--good)}.warn{color:var(--warn)}.muted{color:var(--muted);fill:var(--muted)}
.grid2{display:grid;grid-template-columns:repeat(auto-fit,minmax(560px,1fr));gap:16px}
.chart{max-width:100%;height:auto;font-size:12px}.chart text{fill:var(--fg)}.chart text.muted{fill:var(--muted)}.chart .grid{stroke:var(--line);stroke-dasharray:2 3}
.bar{fill:var(--accent)}.bar.hot{fill:var(--crit)}.db{stroke:#999;stroke-width:3}.db.good{stroke:var(--good)}.db.bad{stroke:var(--crit)}
.flows{display:grid;grid-template-columns:repeat(auto-fill,minmax(520px,1fr));gap:8px 24px}.flow h4{margin:8px 0 2px}.flow-row{display:flex;gap:8px;align-items:flex-start;margin:2px 0}.lbl{width:28px;color:var(--muted);font-size:12px;padding-top:1px}
.stack svg{display:block;border-radius:3px}.legend{display:flex;flex-wrap:wrap;gap:2px 12px;font-size:12px;color:var(--muted);margin-top:2px}.lg i{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:4px;vertical-align:-1px}
.scenario{border:1px solid var(--line);border-radius:6px;padding:4px 16px 8px;margin:10px 0}details summary{cursor:pointer;color:var(--muted)}code{font-size:12px}
footer{padding:12px 32px 32px}footer h3{font-size:14px}footer li{margin:2px 0}
@media print{nav{display:none}.card,.scenario{break-inside:avoid}}
`;
