import { promises as fs } from "node:fs";
import path from "node:path";
import type { AnyReport } from "../index.js";
import type { SimulationResult } from "../core/runner.js";
import type { Insights } from "../insights/insights.js";
import { CSS, badge, embedJson, esc, type HtmlLang } from "./html.js";
import { readReport } from "./io.js";
import { fmtMin, pct } from "./units.js";

/**
 * Static index of saved reports in a directory (docs/dashboard-design.md §8).
 * Lists every readable GDL report JSON (newest first) with headline numbers and a link
 * to the sibling `.html` dashboard when it exists. Unreadable files are listed, not fatal.
 */

export interface IndexEntry {
  /** File name relative to the index directory. */
  file: string;
  html: string | null;
  kind: AnyReport["kind"];
  project: string;
  generatedAt: string;
  modelSha256: string;
  valid: boolean;
  policy: string | null;
  mode: string | null;
  runs: number | null;
  completionRate: number | null;
  medianMinutes: number | null;
  scenarios: number | null;
  findings: { critical: number; warning: number; info: number };
}

export interface ReportIndex {
  dir: string;
  entries: IndexEntry[];
  skipped: { file: string; reason: string }[];
}

export const INDEX_FILE = "index.html";

export async function buildReportIndex(dir: string, insightsFor: (r: AnyReport) => Insights | Promise<Insights>): Promise<ReportIndex> {
  const abs = path.resolve(dir);
  const names = (await fs.readdir(abs).catch(() => [] as string[])).filter((n) => n.toLowerCase().endsWith(".json")).sort();
  const entries: IndexEntry[] = [];
  const skipped: ReportIndex["skipped"] = [];
  for (const name of names) {
    let report: AnyReport;
    try {
      report = await readReport(path.join(abs, name));
    } catch (e) {
      skipped.push({ file: name, reason: (e as Error).message.replace(/^.*?: /, "") });
      continue;
    }
    const ins = await insightsFor(report);
    const f = { critical: 0, warning: 0, info: 0 };
    for (const x of ins.findings) f[x.severity]++;
    const sim: SimulationResult | undefined = report.kind === "compare" ? report.baseline : report.kind === "validate" ? undefined : report.simulation;
    const htmlName = name.replace(/\.json$/i, ".html");
    const hasHtml = await fs.stat(path.join(abs, htmlName)).then((s) => s.isFile(), () => false);
    entries.push({
      file: name,
      html: hasHtml ? htmlName : null,
      kind: report.kind,
      project: report.provenance.project.id,
      generatedAt: report.provenance.generatedAt,
      modelSha256: report.provenance.modelSha256,
      valid: report.validation.ok,
      policy: sim?.policy.id ?? null,
      mode: sim?.mode ?? null,
      runs: sim?.runs ?? null,
      completionRate: sim?.completionRate ?? null,
      medianMinutes: sim?.minutes.median ?? null,
      scenarios: report.kind === "compare" ? report.scenarios.length : null,
      findings: f,
    });
  }
  entries.sort((a, b) => b.generatedAt.localeCompare(a.generatedAt) || a.file.localeCompare(b.file));
  return { dir: abs, entries, skipped };
}

interface IU {
  title: string;
  empty: string;
  thWhen: string;
  thKind: string;
  thProject: string;
  thPolicy: string;
  thRuns: string;
  thCompl: string;
  thMedian: string;
  thFindings: string;
  thModel: string;
  thOpen: string;
  json: string;
  html: string;
  skippedH: string;
  invalid: string;
  hint: string;
  footer: (v: string) => string;
}

const EN_I: IU = {
  title: "Reports",
  empty: "No GDL reports found in this directory. Create one with `gdl simulate <project> --save`.",
  thWhen: "Generated",
  thKind: "Kind",
  thProject: "Project",
  thPolicy: "Policy / mode",
  thRuns: "Runs",
  thCompl: "Completed",
  thMedian: "Median length",
  thFindings: "Findings (C/W/I)",
  thModel: "Model",
  thOpen: "Open",
  json: "JSON",
  html: "Dashboard",
  skippedH: "Ignored files",
  invalid: "invalid model",
  hint: "Compare over time: gdl report <a.json> <b.json> …",
  footer: (v) => `Generated by GDL ${v}.`,
};

const ZH_I: IU = {
  title: "報告列表",
  empty: "此目錄沒有 GDL 報告。可用 `gdl simulate <project> --save` 產生。",
  thWhen: "產生時間",
  thKind: "類型",
  thProject: "專案",
  thPolicy: "策略 / 模式",
  thRuns: "執行數",
  thCompl: "完成率",
  thMedian: "中位數時長",
  thFindings: "發現 (嚴重/警告/資訊)",
  thModel: "模型",
  thOpen: "開啟",
  json: "JSON",
  html: "儀表板",
  skippedH: "略過的檔案",
  invalid: "模型無效",
  hint: "跨時間比較：gdl report <a.json> <b.json> …",
  footer: (v) => `由 GDL ${v} 產生。`,
};

/** Percent-encode each path segment so odd file names stay valid relative links. */
function href(name: string): string {
  return encodeURI(name).replace(/#/g, "%23").replace(/\?/g, "%3F");
}

export function renderIndexHtml(index: ReportIndex, opts: { lang?: HtmlLang; gdlVersion: string }): string {
  const t = opts.lang === "zh-TW" ? ZH_I : EN_I;
  const rows = index.entries.map((e) => {
    const links = [`<a href="${href(e.file)}">${t.json}</a>`, ...(e.html ? [`<a href="${href(e.html)}">${t.html}</a>`] : [])].join(" · ");
    const model = `<span title="${esc(e.modelSha256)}">${esc(e.modelSha256.slice(0, 10))}</span>`;
    return `<tr><td>${esc(e.generatedAt)}</td><td>${esc(e.kind)}${e.scenarios !== null ? ` <small>${e.scenarios} sc.</small>` : ""}${e.valid ? "" : " " + badge("critical", t.invalid)}</td><td>${esc(e.project)}</td><td>${e.policy ? `${esc(e.policy)} · ${esc(e.mode ?? "")}` : "-"}</td><td class="n">${e.runs ?? "-"}</td><td class="n">${e.completionRate === null ? "-" : pct(e.completionRate)}</td><td class="n">${e.medianMinutes === null ? "-" : fmtMin(e.medianMinutes)}</td><td class="n">${e.findings.critical > 0 ? `<b class="bad">${e.findings.critical}</b>` : "0"}/${e.findings.warning > 0 ? `<b class="warn">${e.findings.warning}</b>` : "0"}/${e.findings.info}</td><td>${model}</td><td>${links}</td></tr>`;
  });
  const table = index.entries.length
    ? `<table><thead><tr><th>${t.thWhen}</th><th>${t.thKind}</th><th>${t.thProject}</th><th>${t.thPolicy}</th><th>${t.thRuns}</th><th>${t.thCompl}</th><th>${t.thMedian}</th><th>${esc(t.thFindings)}</th><th>${t.thModel}</th><th>${t.thOpen}</th></tr></thead><tbody>${rows.join("")}</tbody></table>`
    : `<p class="muted">${esc(t.empty)}</p>`;
  const skipped = index.skipped.length ? `<h3>${esc(t.skippedH)}</h3><ul>${index.skipped.map((s) => `<li><code>${esc(s.file)}</code> — ${esc(s.reason)}</li>`).join("")}</ul>` : "";
  return `<!doctype html>
<html lang="${opts.lang === "zh-TW" ? "zh-Hant" : "en"}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="GDL ${esc(opts.gdlVersion)}">
<title>GDL ${esc(t.title)}</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <div class="title"><h1>GDL ${esc(t.title)}</h1><span class="kind">${index.entries.length}</span></div>
  <p class="muted">${esc(t.hint)}</p>
</header>
<main>
<section>${table}${skipped}</section>
</main>
<footer><p class="muted">${esc(t.footer(opts.gdlVersion))}</p></footer>
<script type="application/json" id="gdl-index">${embedJson({ entries: index.entries, skipped: index.skipped })}</script>
</body>
</html>
`;
}
